### ISSUE TITLE
warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found

### ISSUE THREAD

**Issue by sjsongsong** [crawlab-team/crawlab#1080]
在集群环境下，通过docker安装部署了Crawlab

通过docker-compose启动容器

不同的工作节点采用相同的配置（除了IP不同外）

但是部分节点可以正常启动，且mongo可以接收到节点信息，显示online状态

但是部分节点启动后，mongo无法接收到节点信息

docker-compose.yaml配置如下：(除了container_name和CRAWLAB_SERVER_REGISTER_IP外，各个工作节点配置一致)

```yaml
version: '3.3'
services:
  master:
    image: tikazyq/crawlab:latest
    container_name: worker5
    environment:
      CRAWLAB_API_ADDRESS: "https:10.3.1.151:8080"  # backend API address 后端 API 地址. 适用于 https 或者源码部署
      CRAWLAB_SERVER_MASTER: "N"  # whether to be master node 是否为主节点，主节点为 Y，工作节点为 N
      CRAWLAB_MONGO_HOST: "10.3.1.151"  # MongoDB host address MongoDB 的地址，在 docker compose 网络中，直接引用服务名称
      CRAWLAB_MONGO_PORT: "27017"  # MongoDB port MongoDB 的端口
      # CRAWLAB_MONGO_DB: "crawlab_test"  # MongoDB database MongoDB 的数据库
      #CRAWLAB_MONGO_USERNAME: "test"  # MongoDB username MongoDB 的用户名
      #CRAWLAB_MONGO_PASSWORD: "123456"  # MongoDB password MongoDB 的密码
      #CRAWLAB_MONGO_AUTHSOURCE: "admin"  # MongoDB auth source MongoDB 的验证源
      CRAWLAB_REDIS_ADDRESS: "10.3.1.151"  # Redis host address Redis 的地址，在 docker compose 网络中，直接引用服务名称
      CRAWLAB_REDIS_PORT: "6379"  # Redis port Redis 的端口
      #CRAWLAB_REDIS_DATABASE: "1"  # Redis database Redis 的数据库
      CRAWLAB_REDIS_PASSWORD: "****"  # Redis password Redis 的密码
      # CRAWLAB_LOG_LEVEL: "info"  # log level 日志级别. 默认为 info
      # CRAWLAB_LOG_ISDELETEPERIODICALLY: "N"  # whether to periodically delete log files 是否周期性删除日志文件. 默认不删除
      # CRAWLAB_LOG_DELETEFREQUENCY: "@hourly"  # frequency of deleting log files 删除日志文件的频率. 默认为每小时
      CRAWLAB_SERVER_REGISTER_TYPE: "ip"  # node register type 节点注册方式. 默认为 mac 地址，也可设置为 ip（防止 mac 地址冲突）
      CRAWLAB_SERVER_REGISTER_IP: "10.3.1.155"  # node register ip 节点注册IP. 节点唯一识别号，只有当 CRAWLAB_SERVER_REGISTER_TYPE 为 "ip" 时才生效
      CRAWLAB_TASK_WORKERS: 4  # number of task executors 任务执行器个数（并行执行任务数）
      CRAWLAB_RPC_WORKERS: 8  # number of RPC workers RPC 工作协程个数
      # CRAWLAB_SERVER_LANG_NODE: "Y"  # whether to pre-install Node.js 预安装 Node.js 语言环境
      # CRAWLAB_SERVER_LANG_JAVA: "Y"  # whether to pre-install Java 预安装 Java 语言环境
      # CRAWLAB_SETTING_ALLOWREGISTER: "N"  # whether to allow user registration 是否允许用户注册
      # CRAWLAB_SETTING_ENABLETUTORIAL: "N"  # whether to enable tutorial 是否启用教程
      # CRAWLAB_NOTIFICATION_MAIL_SERVER: smtp.exmaple.com  # STMP server address STMP 服务器地址
      # CRAWLAB_NOTIFICATION_MAIL_PORT: 465  # STMP server port STMP 服务器端口
      # CRAWLAB_NOTIFICATION_MAIL_SENDEREMAIL: admin@exmaple.com  # sender email 发送者邮箱
      # CRAWLAB_NOTIFICATION_MAIL_SENDERIDENTITY: admin@exmaple.com  # sender ID 发送者 ID
      # CRAWLAB_NOTIFICATION_MAIL_SMTP_USER: username  # SMTP username SMTP 用户名
      # CRAWLAB_NOTIFICATION_MAIL_SMTP_PASSWORD: password  # SMTP password SMTP 密码
    ports:
      - "8080:8080" # frontend port mapping 前端端口映射
    volumes:
      - "/var/crawlab/log:/var/logs/crawlab" # log persistent 日志持久化

```

容器启动的工作日志如下：

```shell
(base) [mca@clu05 Dockerfile]$ docker-compose up
Creating network "dockerfile_default" with the default driver
Creating worker5 ... done
Attaching to worker5
worker5   |  * Starting nginx nginx
worker5   |    ...done.
worker5   | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
worker5   |  - using env:	export GIN_MODE=release
worker5   |  - using code:	gin.SetMode(gin.ReleaseMode)
worker5   | 
worker5   | [GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (3 handlers)
worker5   | 2022/03/10 22:27:35  info initialized config successfully
worker5   | 2022/03/10 22:27:35  info initialized mongodb successfully
worker5   | 2022/03/10 22:27:35  info initialized redis successfully
worker5   | 2022/03/10 22:27:35  info initialized log config successfully
worker5   | 2022/03/10 22:27:35  info periodically cleaning log is switched off
worker5   | 2022/03/10 22:27:35  info initialized log successfully
worker5   | 2022/03/10 22:27:35  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:36  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:37  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:38  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:39  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:40  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:41  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:42  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:43  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:44  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:45  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:46  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:47  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:48  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:49  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:50  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:51  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:52  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:53  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:54  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found
worker5   | 2022/03/10 22:27:55  warn Get current node info from database failed.  Will after 1.000000 seconds, try again. error=not found

```

发现redis中关于该节点的信息时有时无，mongo的nodes表中则无任何该节点的信息

后来根据redis的节点信息手动在mongo中写入后，节点的状态始终被刷新为offline，以至于该节点一直无法使用。

（个人考虑是由于节点间通信问题导致，但不知道具体问题在哪里）

请问各位是否遇到过类似的问题，如何解决那？或有针对该问题的建议？
