### ISSUE TITLE
admin 通过vscode port登陆失败

### ISSUE THREAD

**Issue by kevinzhangcode** [crawlab-team/crawlab#1116]
**Bug 描述**
我将机器部署在`内网服务器`，通过`vscode`的`port`功能映射到本机打开，例如，当输入用户名和密码均为`admin`
时，登陆功能不工作。
vscode port配置
<img width="990" alt="image" src="https://user-images.githubusercontent.com/38588781/171665745-a5b5bd8d-0f0a-43e5-861d-d1dfde3997d2.png">

登陆错误
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/38588781/171665682-71728074-7674-484d-90ee-2a26e89d1758.png">

**排除其他因素**
远程主机端口`6800`存在`scrapyd`的管理界面，vscode能将远程主机的`6800`映射到本机端口上。
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/38588781/171667080-cec63c4e-0f21-4f0f-9561-d2cd174fc84e.png">

**期望结果**
登陆`admin` 能工作。

**Comment by tikazyq** [comment]
可能需要端口配置，最好提供一些更详细的信息

**Comment by tikazyq** [comment]
可能需要端口配置，最好提供一些更详细的信息

**Comment by kevinzhangcode** [comment]
@tikazyq 
这是我的配置文件
`docker-compose.yml`
```
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: Y  # Y: 主节点
      CRAWLAB_MONGO_HOST: mongo  # mongo host address. 在 Docker-Compose 网络中，直接引用 service 名称
      CRAWLAB_MONGO_PORT: 7990  # mongo port 
      CRAWLAB_MONGO_DB: crawlab  # mongo database 
      CRAWLAB_MONGO_USERNAME: admin  # mongo username
      CRAWLAB_MONGO_PASSWORD: 123456  # mongo password 
      CRAWLAB_MONGO_AUTHSOURCE: admin  # mongo auth source 
    volumes:
      - "/home/xxxx/mycrawlab/master:/data"  # 持久化 crawlab 数据
    ports:
      - "7991:8080"  # 开放 api 端口
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # mongo username
      MONGO_INITDB_ROOT_PASSWORD: 123456  # mongo password
    volumes:
      - "/home/xxxx/mycrawlab/data/db:/data/db"  # 持久化 mongo 数据
    ports:
      - "7990:27017"  # 开放 mongo 端口到宿主机
```
docker容器检查
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/38588781/171798638-d8134f2e-3edf-433c-832d-0734ec1b2b84.png">
