### ISSUE TITLE
Docker部署方式所有的新建操作均失败，提示“controller error: request payload invalid”

### ISSUE THREAD

**Issue by J0o1h** [crawlab-team/crawlab#1151]
**Describe the bug**
Docker 部署方式所有的新建操作均失败

**docker-compose setting**
```
version: '3.3'
services:
  master: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    container_name: crawlab_example_mongo
    restart: always
```

**Error Log**
```
controller error: request payload invalid
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220716061416-53097a1f65d1/controllers/utils_http.go:13 github.com/crawlab-team/crawlab-core/controllers.handleError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220716061416-53097a1f65d1/controllers/utils_http.go:23 github.com/crawlab-team/crawlab-core/controllers.HandleError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220716061416-53097a1f65d1/controllers/utils_http.go:31 github.com/crawlab-team/crawlab-core/controllers.HandleErrorBadRequest()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220716061416-53097a1f65d1/controllers/delegate_list.go:124 github.com/crawlab-team/crawlab-core/controllers.(*ListControllerDelegate).PutList()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220716061416-53097a1f65d1/middlewares/auth.go:48 github.com/crawlab-team/crawlab-core/middlewares.AuthorizationMiddleware.func1()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.1-0.20220716061416-53097a1f65d1/middlewares/cors.go:17 github.com/crawlab-team/crawlab-core/middlewares.CORSMiddleware.func1()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101 github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/logger.go:240 github.com/gin-gonic/gin.LoggerWithConfig.func1()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 github.com/gin-gonic/gin.(*Engine).ServeHTTP()
/usr/local/go/src/net/http/server.go:2868 net/http.serverHandler.ServeHTTP()
/usr/local/go/src/net/http/server.go:1933 net/http.(*conn).serve()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
```

**To Reproduce**
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/4597456/180682257-50dc2a79-7dcb-4480-9642-ffcae7d990ea.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/4597456/180682301-c85e6617-4098-467d-af0d-9f7ac867311b.png">

<img width="825" alt="image" src="https://user-images.githubusercontent.com/4597456/180682354-a5a6aa36-a32b-421d-9875-fe644fab9037.png">
