### ISSUE TITLE
 扫描任务日志不实时刷新，需要等任务结束后才能获取到日志信息

### ISSUE THREAD

**Issue by J0o1h** [crawlab-team/crawlab#1153]
**Bug 描述**
新建扫描任务， 扫描任务详情中日志不实时刷新，需要等任务结束后才能获取到日志信息。在最新版本下测试的。

**复现步骤**
该 Bug 复现步骤如下
1.  新建爬虫
3.  开始扫描
4.  查看任务日志详情

**配置如下**
```
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: mongo
    ports:
      - "8080:8080" # frontend port mapping 前端端口映射
      - "9666:9666" # grpc address
    depends_on:
      - mongo
    volumes:
      - "/Code/go/src/vuln-crawlab/data/master:/root/.crawlab"
  worker:
    image: crawlabteam/crawlab
    container_name: crawlab_worker
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_GRPC_ADDRESS: "master"  # grpc address
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    depends_on:
      - master
    volumes:
      - "/Code/go/src/vuln-crawlab/data/worker:/root/.crawlab"
  mongo:
    image: mongo:4.2
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - "/Code/go/src/vuln-crawlab/data/mongo:/data/db"  # data persistent 持久化数据
    ports:
      - "27017:27017"  # expose port to host machine 暴露接口到宿主机
```

**爬虫脚本如下**
```
#-*- coding : utf-8 -*-
# coding: utf-8
import time

def run():
	print('aaaa')

	time.sleep(30)
	
	print('Successfully saved to mongodb!')


if __name__ == '__main__':
	run()
```

**期望结果**
日志能实时刷新，并显示出来

**截屏**
![image](https://user-images.githubusercontent.com/4597456/180700307-0a350e4f-9fb2-4b5f-8db3-77b53b1ecde0.png)
![image](https://user-images.githubusercontent.com/4597456/180700374-6ba71838-f0db-4040-b157-22db22a75b27.png)
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/4597456/180710678-3a252e20-db0d-4ccb-8d90-699c8506b371.png">
