### ISSUE TITLE
work节点无法更新使用

### ISSUE THREAD

**Issue by p59082644** [crawlab-team/crawlab#1225]
**Bug 描述**
工作节点在平台上添加成功，爬虫任务指派后长时间不显示，子节点安装包和现有环境信息，主节点也没有显示。
我在一个节点上 按照你们github 的部署方式，其他节点是可以工作的，跨节点就工作不起来了。
尝试修改work节点容器 pip源， 在master节点上也没有反应。
直接在pip 安装包，基本上都是秒装成功。
**期望结果**
能够正常工作。
**截屏** 
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/15334269/199905292-cc8525d0-67ee-4c66-8007-00f73ff79205.png">
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/15334269/199905349-0ebf8b09-315d-4b51-a7a3-37d59f2fb9dd.png">
<img width="777" alt="image" src="https://user-images.githubusercontent.com/15334269/199906550-cbe8c72a-6d1f-4043-a633-59d94cda490d.png">

**Comment by tikazyq** [comment]
可以去掉敏感信息发一下配置么 docker-compose.yml

另外还可以将docker日志附上

**Comment by p59082644** [comment]
docker  master和work 节点完全按照 官网的方法来安装的。
下面是work节点docker 情况
![image](https://user-images.githubusercontent.com/15334269/200158732-35099d11-f758-4e85-9e84-ffe65981d539.png)

我尝试在主节点的机器上 也安装了一个工作节点。 他们在同一个服务器上一切工作正常。 而在另外一个服务器上的节点，始终无法安装包，也无法执行爬虫任务。 但是在节点管理，节点显示是正常的。
![image](https://user-images.githubusercontent.com/15334269/200158755-fae9f221-cbe4-45d4-8036-66d8b8e1cecd.png)

```
# 工作节点
version: '3.3'
services:
  worker:
    image: crawlabteam/crawlab
    container_name: crawlab_worker
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "N"  # N: 工作节点
      CRAWLAB_GRPC_ADDRESS: "<master_node_ip>:9666"  # grpc address
      CRAWLAB_FS_FILER_URL: "http://<master_node_ip>:8080/api/filer"  # seaweedfs api
    volumes:
      - "/opt/crawlab/master:/data"  # 持久化 crawlab 数据
```
