### ISSUE TITLE
环境变量传入MONGO_DB只能为crawlab_test,不能自定义数据库名。

### ISSUE THREAD

**Issue by k-fire** [crawlab-team/crawlab#125]

**Comment by wo10378931** [comment]
可以的呀~  
```
mongo:
  host: "192.168.235.26"
  port: 27017
  db: crawlab_local
  username: "root"
  password: "example"
  authSource: "admin"
```
