### ISSUE TITLE
上传文件超时

### ISSUE THREAD

**Issue by zchcc** [crawlab-team/crawlab#1299]
**Bug 描述**
上传任意文件前端都504超时，看了一下控制台，seaweed在报错，可能有关系吧，但是不理解为什么报没空间

**复现步骤**
该 Bug 复现步骤如下
1. 通过docker compose 部署
```yaml
version: '3'
services:
  crawlab:
    container_name: crawlab_master
    image: "crawlabteam/crawlab:latest"
    pull_policy: always
    ports:
      - "18808:8080"
    volumes:
      - "/share/Container/crawlab/.crawlab:/root/.crawlab"  # 持久化 crawlab 元数据
      - "/share/Container/crawlab/data:/data"  # 持久化 crawlab 数据
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y"  # Y: 主节点
      CRAWLAB_MONGO_HOST: "mongodb"  # mongo host address. 在 Docker-Compose 网络中，直接引用 service 名称
      CRAWLAB_MONGO_PORT: "27017"  # mongo port
      CRAWLAB_MONGO_DB: "crawlab"  # mongo database
      CRAWLAB_MONGO_USERNAME: "root"  # mongo username
      CRAWLAB_MONGO_PASSWORD: "87654321"  # mongo password
      CRAWLAB_MONGO_AUTHSOURCE: "admin"  # mongo auth source
    depends_on:
      - mongodb
    networks:
      - develop_net
  mongodb:
    container_name: mongodb
    image: "mongo:4.2"
    ports:
      - "27017:27017"  # 开放 mongo 端口到宿主机
    volumes:
      - "/share/Container/mongo/data/db:/data/db"  # 持久化 mongo 数据
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"  # mongo username
      MONGO_INITDB_ROOT_PASSWORD: "87654321"  # mongo password
    networks:
      - develop_net
networks:
  develop_net:
```

**期望结果**
能工作。

**截屏**
- 前端报错信息
  ![crawlab_save_504_1](https://user-images.githubusercontent.com/2937437/232322659-fe94a1c3-45eb-41b5-9acb-a9015a9d35b1.png)
  ![crawlab_save_504_2](https://user-images.githubusercontent.com/2937437/232322662-706ead73-772f-43de-9f42-55437fd5737a.png)
- crawlab容器日志
  [_crawlab_master_logs.txt](https://github.com/crawlab-team/crawlab/files/11242623/_crawlab_master_logs.txt)
- crawlab容器内信息
  ![crawlab](https://user-images.githubusercontent.com/2937437/232322665-6ebb696d-1466-4a60-a89b-167984c286ea.png)
