### ISSUE TITLE
执行 docker-compose down 后，重新 docker-compose up 运行容器时，日志没有持久化。

### ISSUE THREAD

**Issue by D0ggy** [crawlab-team/crawlab#1356]
**环境版本**
>win 10
>crawlab Community v0.6.1

**Describe the bug**
[参考文档](https://docs.crawlab.cn/zh/guide/installation/docker.html#%E5%8D%95%E8%8A%82%E7%82%B9%E9%83%A8%E7%BD%B2)想持久化数据，执行 docker-compose down 后，重新 docker-compose up 运行容器，日志没有持久化，而其他的爬虫，任务，数据等可以持久化。

**我的 docker-compose.yml**
```yml
version: '3.3'
services:
  master:
    build:
      context: .
      dockerfile: Crawllab.Dockerfile
      #    image: crawlabteam/crawlab:0.6.2
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    volumes:
      - "./data/.crawlab/master:/root/.crawlab"  # 持久化 crawlab 元数据
      - "./data/crawlab/master:/data"  # 持久化 crawlab 数据
      - "./script/:/app/script/"  # 持久化 crawlab 数据
    ports:
      - "12987:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0-rc
    volumes:
      - "./data/crawlab/mongo/data/db:/data/db"  # 持久化 mongo 数据

```

**Comment by tikazyq** [comment]
Thanks for your feedback! This indeed is something missing on the documentation.

You should persist the directory of `/var/log/crawlab`.

In your case, it should be as below.

```yaml
version: '3.3'
services:
  master:
    build:
      context: .
      dockerfile: Crawllab.Dockerfile
      #    image: crawlabteam/crawlab:0.6.2
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    volumes:
      - "./data/.crawlab/master:/root/.crawlab"  # 持久化 crawlab 元数据
      - "./data/crawlab/master:/data"  # 持久化 crawlab 数据
      - "./script/:/app/script/"  # 持久化 crawlab 数据
      - "./data/crawlab/master-log:/var/log/crawlab"  # 持久化 crawlab 日志数据
    ports:
      - "12987:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0-rc
    volumes:
      - "./data/crawlab/mongo/data/db:/data/db"  # 持久化 mongo 数据
 ```
