### ISSUE TITLE
Crawlab Pro (permanent) doesn't create separate worker nodes

### ISSUE THREAD

**Issue by Voyewodayer** [crawlab-team/crawlab#1379]
**Describe the bug**

On crawlab pro (permanent) version multiple deployed worker nodes are interpreted as one and the same worker. That is more than one workers being deployed shows only one worker node in master node panel. Adding new one just registers this one worker node again instead of making a separate one.

**To Reproduce**

1. Create worker node on separate machine (for example AWS EC2 instance)
2. See that it creates and registers new worker node on master node panel
3. Create another worker node on another machine
4. See on master node panel that it registers existing worker node again instead of creating another node

**Expected behavior**

Each deployed worker should create a new node on the server instead of registering already existing one again.

**Screenshots**
Docker logs for each worker instance show successful connection to master node but aren't shown on its panel as separate entities.

![obraz](https://github.com/crawlab-team/crawlab/assets/65357788/b61cb4af-7ac9-4939-97a4-af34617b7069)

**Comment by tikazyq** [comment]
Hi, thanks for your feedback. Can you upload your config files (docker-compose.yml) after removing sensitive info?

**Comment by Voyewodayer** [comment]
Sure

Master node:
```yml
version: '3.3'
services:
  crawlab:
    image: crawlabteam/crawlab-pro
    container_name: crawlab
    restart: always
    environment:
      - CRAWLAB_LICENSE
      - CRAWLAB_NODE_MASTER
      - CRAWLAB_MONGO_HOST
      - CRAWLAB_MONGO_PORT
      - CRAWLAB_MONGO_DB
      - CRAWLAB_MONGO_USERNAME
      - CRAWLAB_MONGO_PASSWORD
      - CRAWLAB_MONGO_AUTHSOURCE
    volumes:
      - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
      - "/opt/crawlab/master:/data"  # persistent crawlab data
    ports:
      - "9666:9666"  # exposed grpc port
```

Each worker node has this compose file:
```yml
version: '3.3'
services:
  worker:
    image: crawlabteam/crawlab-pro
    container_name: crawlab_worker
    restart: always
    environment:
      CRAWLAB_LICENSE: "${CRAWLAB_LICENSE}"
      CRAWLAB_NODE_MASTER: "N"  # N: worker node
      CRAWLAB_GRPC_ADDRESS: "${MASTER_NODE_IP}:9666"  # grpc address
      CRAWLAB_FS_FILER_URL: "http://${MASTER_NODE_IP}/api/filer"  # seaweedfs api
    volumes:
      - "/opt/.crawlab/worker:/root/.crawlab"  # persistent crawlab metadata
      - "/opt/crawlab/worker:/data"  # persistent crawlab data
```

Mongo is run as separate service


I previously had similar config on free version of Crawlab and it worked properly. Starting with pro version the issue I described above happens, docker logs for worker containers show that each worker node receives the very same ID which probably makes it so it registers the same worker node again instead of creating separate one.
