### ISSUE TITLE
docker部署master启动ngnix异常

### ISSUE THREAD

**Issue by geosmart** [crawlab-team/crawlab#1381]
```bash
 hosts  docker logs -f crawlab_master                                                                                                   
 * Starting nginx nginx                                                                                                                   
   ...fail!                                                                                                                               
Using config file: /app/backend/conf/config.yml                                                                                                                                                                                                                                     
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.                                                 
 - using env:   export GIN_MODE=release                                                                                                   
 - using code:  gin.SetMode(gin.ReleaseMode)                                                                                              
                                                                                                                                          
2023/08/12 11:02:38  info initialized controllers successfully                                                                            
2023/08/12 11:02:38  info initialized middlewares successfully                                                                                                                                                                                                                      
2023/08/12 11:02:38  info initialized routes successfully                                                                                 
[GIN-debug] GET    /nodes/:id                --> github.com/crawlab-team/crawlab-core/controllers.ListController.Get-fm (5 handlers)    
[GIN-debug] GET    /nodes                    --> github.com/crawlab-team/crawlab-core/controllers.ListController.GetList-fm (5 handlers)
[GIN-debug] PUT    /nodes                    --> github.com/crawlab-team/crawlab-core/controllers.ListController.Put-fm (5 handlers)
......
[GIN-debug] POST   /tokens/:id               --> github.com/crawlab-team/crawlab-core/controllers.ListController.Post-fm (5 handlers)
[GIN-debug] POST   /tokens                   --> github.com/crawlab-team/crawlab-core/controllers.ListController.PostList-fm (5 handlers)
[GIN-debug] DELETE /tokens/:id               --> github.com/crawlab-team/crawlab-core/controllers.ListController.Delete-fm (5 handlers)
[GIN-debug] DELETE /tokens                   --> github.com/crawlab-team/crawlab-core/controllers.ListController.DeleteList-fm (5 handlers)
[GIN-debug] GET    /plugin-proxy/:name/*path --> github.com/crawlab-team/crawlab-core/controllers.(*pluginProxyContext).do-fm (5 handlers)
[GIN-debug] POST   /plugin-proxy/:name       --> github.com/crawlab-team/crawlab-core/controllers.(*pluginProxyContext).do-fm (5 handlers)
[GIN-debug] POST   /plugin-proxy/:name/*path --> github.com/crawlab-team/crawlab-core/controllers.(*pluginProxyContext).do-fm (5 handlers)
[GIN-debug] GET    /gits/:id                 --> github.com/crawlab-team/crawlab-core/controllers.ListController.Get-fm (5 handlers)
[GIN-debug] GET    /gits                     --> github.com/crawlab-team/crawlab-core/controllers.ListController.GetList-fm (5 handlers)
[GIN-debug] PUT    /gits                     --> github.com/crawlab-team/crawlab-core/controllers.ListController.Put-fm (5 handlers)
[GIN-debug] PUT    /gits/batch               --> github.com/crawlab-team/crawlab-core/controllers.ListController.PutList-fm (5 handlers)
[GIN-debug] POST   /gits/:id                 --> github.com/crawlab-team/crawlab-core/controllers.ListController.Post-fm (5 handlers)
[GIN-debug] POST   /gits                     --> github.com/crawlab-team/crawlab-core/controllers.ListController.PostList-fm (5 handlers)
[GIN-debug] DELETE /gits/:id                 --> github.com/crawlab-team/crawlab-core/controllers.ListController.Delete-fm (5 handlers)
[GIN-debug] DELETE /gits                     --> github.com/crawlab-team/crawlab-core/controllers.ListController.DeleteList-fm (5 handlers)
[GIN-debug] POST   /login                    --> github.com/crawlab-team/crawlab-core/controllers.(*loginContext).login-fm (4 handlers)
[GIN-debug] POST   /logout                   --> github.com/crawlab-team/crawlab-core/controllers.(*loginContext).logout-fm (4 handlers)
[GIN-debug] GET    /version                  --> github.com/crawlab-team/crawlab-core/controllers.GetVersion (4 handlers)
[GIN-debug] GET    /filer/*path              --> github.com/crawlab-team/crawlab-core/controllers.(*filerContext).do-fm (5 handlers)
[GIN-debug] POST   /filer/*path              --> github.com/crawlab-team/crawlab-core/controllers.(*filerContext).do-fm (5 handlers)
[GIN-debug] PUT    /filer/*path              --> github.com/crawlab-team/crawlab-core/controllers.(*filerContext).do-fm (5 handlers)
[GIN-debug] DELETE /filer/*path              --> github.com/crawlab-team/crawlab-core/controllers.(*filerContext).do-fm (5 handlers)
2023/08/12 11:02:38  info grpc server listens to 0.0.0.0:9666
2023/08/12 11:02:38  info master[f8f3d122-3751-11ee-bbb5-0242ac150003] exists in db
2023/08/12 11:02:38  info updated master[f8f3d122-3751-11ee-bbb5-0242ac150003] in db. id: 64d6f53df807e14f4ce609fb
2023/08/12 11:02:38  info master[f8f3d122-3751-11ee-bbb5-0242ac150003] monitoring started
2023/08/12 11:02:38  info cron: start              
grpc error: stream not found
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/server/server.go:132 github.com/crawlab-team/crawlab-core/grpc/server.(*Server).GetSubscribe()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:213 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:99 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
grpc error: stream not found
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/server/server.go:132 github.com/crawlab-team/crawlab-core/grpc/server.(*Server).GetSubscribe()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:213 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:99 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
grpc error: stream not found
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/server/server.go:132 github.com/crawlab-team/crawlab-core/grpc/server.(*Server).GetSubscribe()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:213 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:99 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
grpc error: stream not found
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/server/server.go:132 github.com/crawlab-team/crawlab-core/grpc/server.(*Server).GetSubscribe()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:213 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:99 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
node error: monitor error
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:236 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:99 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
node error: monitor error
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:236 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/master_service.go:99 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
2023/08/12 11:02:38  info [NodeServer] master received subscribe request from node[8f11b4dd-38b2-11ee-84ef-0242ac170005]
2023/08/12 11:02:38  info [NodeServer] master subscribed node[8f11b4dd-38b2-11ee-84ef-0242ac170005]
2023/08/12 11:02:38  info [NodeServer] updated worker[8f11b4dd-38b2-11ee-84ef-0242ac170005] in db. id: 64d6f53df807e14f4ce609fd
2023/08/12 11:02:38  info [NodeServer] master registered worker[8f11b4dd-38b2-11ee-84ef-0242ac170005]
2023/08/12 11:02:38  info [NodeServer] master received subscribe request from node[8ef35b6e-38b2-11ee-8ebd-0242ac170004]
2023/08/12 11:02:38  info [NodeServer] master subscribed node[8ef35b6e-38b2-11ee-8ebd-0242ac170004]
2023/08/12 11:02:38  info [NodeServer] updated worker[8ef35b6e-38b2-11ee-8ebd-0242ac170004] in db. id: 64d6f53df807e14f4ce609fe
2023/08/12 11:02:38  info [NodeServer] master registered worker[8ef35b6e-38b2-11ee-8ebd-0242ac170004]
```

mongodb数据库已经正常初始化了，但是nginx还是报错

```yml
version: '3.3'
services:
  master: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_master
    networks:
      - db
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "172.21.0.2"
      CRAWLAB_MONGO_PORT: "27017"
      CRAWLAB_MONGO_DB: "crawlab"
      CRAWLAB_MONGO_USERNAME: "admin"
      CRAWLAB_MONGO_PASSWORD: "admin"
      CRAWLAB_MONGO_AUTHSOURCE: "admin"
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:    
      - "8080:8080"

  worker01: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_worker01
    networks:
      - db
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - "./.crawlab/worker01:/root/.crawlab"
    depends_on:
      - master

  worker02: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_worker02
    networks:
      - db
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - "./.crawlab/worker02:/root/.crawlab"
    depends_on:
      - master

networks:
  db:
    external: true
```
