### ISSUE TITLE
镜像架构问题

### ISSUE THREAD

**Issue by heqiang** [crawlab-team/crawlab#1498]
**请描述该需求尝试解决的问题**
我电脑的系统是mac的,arm64的,你们的镜像好像只有amd64的，是否可以提供arm的镜像呢

**Comment by cpython666** [comment]
兄弟，我使用mac m3pro也遇到了你的这个问题，在询问了gpt之后找到了解决方案，非常的简单，只需要在docker-compose.yml中添加一行命令即可。指定platform。只改变这一行代码即可成功运行。🤩🥳
```
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    platform: linux/amd64
    container_name: crawlab_master
```
