### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by ruvn-1fgas** [crawlab-team/crawlab#1541]
**Describe the bug**
Worker is restaring after running any task

**Logs**

```log
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit()
invalid character 'p' after top-level value
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.3-0.20231031044528-37e6d73eb203/task/handler/service.go:409 github.com/crawlab-team/crawlab-core/task/handler.(*Service).run()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.3-0.20231031044528-37e6d73eb203/task/handler/service.go:119 github.com/crawlab-team/crawlab-core/task/handler.(*Service).Fetch()
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit()
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x170739f]
```

**To Reproduce**

We are deploying it to kubernetes, so here it is:
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlab-worker
  namespace: crawlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawlab-worker
  template:
    metadata:
      labels:
        app: crawlab-worker
    spec:
      containers:
      - image: crawlabteam/crawlab:latest
        imagePullPolicy: IfNotPresent
        name: crawlab
        env:
        - name: CRAWLAB_NODE_MASTER
          value: "N"
        - name: CRAWLAB_GRPC_ADDRESS
          value: "IP:HOST"
        - name: CRAWLAB_FS_FILER_URL
          value: "http://IP/api/filter"
      restartPolicy: Always
 ```

1. Run any task on worker
