### ISSUE TITLE
docker-compose文件的一个错误

### ISSUE THREAD

**Issue by qingfengfenga** [crawlab-team/crawlab#171]
以下是文档提供的docker-compose文件，按照文档的设置，并不能启动工作节点，查看日志发现工作节点无法连接redis，修改worker下`CRAWLAB_REDIS_ADDRESS: "redis:6379"`为`CRAWLAB_REDIS_ADDRESS: "redis"`后可以正常运行工作节点。（只针对所有容器在同一宿主机的情况），如果测试正确的话，请及时修正文档。
```
version: '3.3'
services:
  master: 
    image: tikazyq/crawlab:latest
    container_name: crawlab-master
    environment:
      CRAWLAB_API_ADDRESS: "192.168.99.100:8000"
      CRAWLAB_SERVER_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
    ports:    
      - "8080:8080" # frontend
      - "8000:8000" # backend
    depends_on:
      - mongo
      - redis
  worker:
    image: tikazyq/crawlab:latest
    container_name: crawlab-worker
    environment:
      CRAWLAB_SERVER_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis:6379"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
```
