### ISSUE TITLE
使用外部mongo和Redis，依旧出现no reachable servers

### ISSUE THREAD

**Issue by kanadeblisst** [crawlab-team/crawlab#390]
**Describe the bug**
我在台式机开了一个虚拟机运行crawlab，使用服务器的mongo和Redis正常运行。但是将虚拟机拷贝一份到笔记本上再次运行时报no reachable servers，我确认mongo是可以连接的，因为我在笔记本的虚拟机上是可以通过mongo命令连接到服务器的。台式和笔记本虚拟机的区别仅仅是网络环境不同，其他都是拷贝过去的，而命令行能连接说明网络环境也不是问题。希望您能帮助我找到原因。

docker-compose.yml文件如下：
```
version: '3.3'
services:
  master: 
    image: tikazyq/crawlab:latest
    container_name: crawlab-master
    environment:
      CRAWLAB_API_ADDRESS: "http://172.29.2.1:8000"
      CRAWLAB_SERVER_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "*.*.*.*"
      CRAWLAB_MONGO_PORT: 27017
      CRAWLAB_REDIS_ADDRESS: "*.*.*.*"
      CRAWLAB_REDIS_PASSWORD: "*"
      CRAWLAB_REDIS_PORT: 6379
    ports:    
      - "8080:8080" # frontend
      - "8000:8000" # backend
  worker:
    image: tikazyq/crawlab:latest
    container_name: crawlab-worker
    environment:
      CRAWLAB_MONGO_HOST: "*.*.*.*"
      CRAWLAB_MONGO_PORT: 27017
      CRAWLAB_REDIS_ADDRESS: "*.*.*.*"
      CRAWLAB_REDIS_PASSWORD: "*"
      CRAWLAB_REDIS_PORT: 6379

```
