### ISSUE TITLE
附属到已有项目的 docker-compose 中, 登录失败

### ISSUE THREAD

**Issue by SYFH** [crawlab-team/crawlab#393]
这是修改后的 docker-compose:
```
version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./cer:/etc/nginx/certs
      - /var/log/nginx:/var/log/nginx
    links:
      - flask
      - master
    ports:
      - 443:443
      - 80:80
  flask:
    volumes:
      - /var/log/nginx:/var/log/nginx
    build:
      context: ./flask
  master: 
    image: tikazyq/crawlab:latest
    container_name: crawlab-master
    environment:
      CRAWLAB_API_ADDRESS: "crawlab.xxx.com"
      CRAWLAB_SERVER_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "xxxxxx"
      CRAWLAB_REDIS_ADDRESS: "xxxxxx"
    ports:    
      - "8080:8080" # frontend
      - "8000:8000" # backend
  worker:
    image: tikazyq/crawlab:latest
    container_name: crawlab-worker
    environment:
      CRAWLAB_SERVER_MASTER: "N"
      CRAWLAB_MONGO_HOST: "xxxxxx"
      CRAWLAB_REDIS_ADDRESS: "xxxxxx"
```

nginx 配置添加了一段:
```
server {
    listen 80;
    server_name crawlab.xxx.com;
    listen [::]:80;
    server_tokens off;
    client_max_body_size 100M;

    access_log  /var/log/nginx/nginx.api.access.log;
    error_log   /var/log/nginx/nginx.api.error.log;

    location / {
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Host \$http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://master:8080;
        proxy_redirect off;
    }
}
```

现在是访问 crawlab.xxx.com 可以正常打开界面, 但登录失败, F12 看请求记录发现是 404, 登录 API 是`http://crawlab.xxx.com/crawlab.xxx.com/login`

如果 CRAWLAB_API_ADDRESS 设置成主机公网IP, 登录 API 就是 `http://crawlab.xxx.com/xxx.xxx.xxx.xxx/login` 了, 依然是登录失败

想问一下这种情况该怎么解决?
