### ISSUE TITLE
可配置爬虫嵌套跳转多次，爬取结果为空且报错

### ISSUE THREAD

**Issue by jackcily** [crawlab-team/crawlab#898]
**Bug 描述**
我想实现点击3个阶段的url跳转，但是好像并不支持这个功能。

**复现步骤**
对应的Spiderfile在此
```yaml
name: toscrapy_books
display_name: ""
col: ""
remark: ""
type: ""
engine: scrapy
start_url: https://www.tp-link.com/us/support/download/
start_stage: list
stages:
- name: list
  is_list: true
  list_css: div[data-class="wi-fi-routers"] > .item-box > span
  list_xpath: ""
  page_css: ""
  page_xpath: ""
  page_attr: ""
  fields:
  - name: title
    css: a.ga-click
    xpath: ""
    attr: ""
    next_stage: ""
    remark: ""
  - name: url
    css: a.ga-click
    xpath: ""
    attr: href
    next_stage: detail
    remark: ""
- name: detail
  is_list: false
  list_css: .nav-tabs-box
  list_xpath: ""
  page_css: ""
  page_xpath: ""
  page_attr: ""
  fields:
  - name: content
    css: a[href="#Firmware"]
    xpath: ""
    attr: href
    next_stage: stage_firm
    remark: ""
- name: stage_firm
  is_list: false
  list_css: .download-list
  list_xpath: ""
  page_css: ""
  page_xpath: ""
  page_attr: ""
  fields:
  - name: field_1610093457186
    css: h1
    xpath: ""
    attr: ""
    next_stage: ""
    remark: ""
settings:
  ROBOTSTXT_OBEY: "false"
  USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
cmd: ""

```

**期望结果**
能够实现多次嵌套跳转。
