### ISSUE TITLE
Tracking user behaviours without user consent

### ISSUE THREAD

**Issue by ttimasdf** [crawlab-team/crawlab#944]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2762704/114363678-3a9cce80-9bab-11eb-8b53-b397ddf88836.png)

You know what it means, it's clearly by design and cannot be disabled at all.

**To Reproduce**
1. Open Developer Tools.
2. Enter any page inside crawlab
2. unknown API calls shown above

**Expected behavior**

`Allow Sending Statistics` option *should allow users to disallow* 👎 

**Screenshots**

Posted in description.

**Comment by tikazyq** [comment]
Currently the tracking server is down. Will fix and allow disabling in later release.

**Comment by tikazyq** [comment]
Currently the tracking server is down. Will fix and allow disabling in later release.

**Comment by ttimasdf** [comment]
Added CSP policy in load balancer as a workaround.

```yml
version: '3.3'
services:
  master:
# ...
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gateway"
      - "traefik.http.routers.crawlab.rule=Host(`crawlab.custom.domain`)"
      - "traefik.http.routers.crawlab.tls=true"
      - "traefik.http.routers.crawlab.middlewares=csp-trusted"
      - "traefik.http.services.crawlab-web.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.csp-trusted.headers.contentSecurityPolicy=default-src 'self' *.custom.domain"
```
