### ISSUE TITLE
gRPC Client Cannot Connect to the master node!

### ISSUE THREAD

**Issue by edmund-zhao** [crawlab-team/crawlab#994]
**Bug**

When I tried building CRAWLAB by docker, worker node cannot connect the master node.

**YML File**
```
version: '3.3'
services:
  master: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_GRPC_SERVER_ADDRESS: "0.0.0.0:9666"
      CRAWLAB_SERVER_HOST: "0.0.0.0"
      CRAWLAB_GRPC_AUTHKEY: "youcanneverguess"
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:    
      - "8080:8080"
      - "9666:9666"
      - "8000:8000"
    depends_on:
      - mongo

  worker01: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_worker01
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "MY_Public_IP_Address:9666"
      CRAWLAB_GRPC_AUTHKEY: "youcanneverguess"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - "./.crawlab/worker01:/root/.crawlab"
    depends_on:
      - master

  mongo:
    image: mongo:latest
    container_name: crawlab_example_mongo
    restart: always
```
![image](https://user-images.githubusercontent.com/53864204/128676865-ea3eebd1-7079-45e9-8273-4cf6c909ba87.png)
