### ISSUE TITLE
最新master的代码，不能正常通过docker启动

### ISSUE THREAD

**Issue by zires** [crawlab-team/crawlab#997]
**Bug 描述**
最新master的代码，不能正常通过docker启动

**复现步骤**
1. 拉取最新的代码
2. docker-compose up
3. 报错：2021/08/10 17:44:51 error grpc client connect error: grpc error: client failed to start. reattempt in 51.7 seconds
4. 拉取`517ae21e13a57e0d9c074b162793aee689f99c0d `
5. docker-compose up
6. 正常运行

**期望结果**
docker能正常工作。

**截屏**
![image](https://user-images.githubusercontent.com/108843/128954987-86a1d57b-3e4f-49ae-a124-88c8bcfdd6c9.png)

**Comment by zires** [comment]
#994 是否和这个问题类似？

**Comment by biglin** [comment]
遇到同样的问题

**Comment by tikazyq** [comment]
Fixed on https://github.com/crawlab-team/crawlab/commits/develop. 

Please pull the latest image of develop branch for test:
```bash
docker pull crawlabteam/crawlab:develop
```

Below are the docker compose config files:

Master Node (Example IP: 192.168.0.101):
```yaml
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab:develop
    container_name: crawlab_develop_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:
      - "8080:8080" # expose port for web/api
      - "9666:9666" # expose port for grpc
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: crawlab_develop_mongo
```

Worker Node (Example IP: 192.168.0.102):
```yaml
version: '3.3'
services:
  worker01:
    image: crawlabteam/crawlab:develop
    container_name: crawlab_develop_worker01
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "192.168.0.101" # point to master node
      CRAWLAB_FS_FILER_URL: "http://192.168.0.101:8080/api/filer" # point to master node
    volumes:
      - "./.crawlab/worker01:/root/.crawlab"
```

**Comment by edmund-zhao** [comment]
ACTIVE IN DEBIAN 10, NEGATIVE IN UBUNTU 21.04

**Comment by edmund-zhao** [comment]
worker nodes can find on panel. Unfortunately, worker nodes frequently will show offline.

```sh
crawlab_develop_master | 2021/08/12 17:24:44 error cannot ping worker[60f1ab03-fb4b-11eb-9ed6-0242ac170002]: grpc error: stream not found
crawlab_develop_master | grpc error: stream not found
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:220 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:98 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
crawlab_develop_master | /usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit()
crawlab_develop_master | 2021/08/12 17:24:44 error cannot ping worker[717080d7-f9bd-11eb-81d4-0242ac120004]: grpc error: stream not found
crawlab_develop_master | grpc error: stream not found
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:220 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:98 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
crawlab_develop_master | /usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit()
crawlab_develop_master | node error: monitor error
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:11 github.com/crawlab-team/go-trace.TraceError()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:230 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:98 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
crawlab_develop_master | /usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit()
crawlab_develop_master | node error: monitor error
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:11 github.com/crawlab-team/go-trace.TraceError()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:230 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).monitor()
crawlab_develop_master | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210811.1634/node/service/master_service.go:98 github.com/crawlab-team/crawlab-core/node/service.(*MasterService).Monitor()
crawlab_develop_master | /usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit()

```

![image](https://user-images.githubusercontent.com/53864204/129173711-3e841b23-20cf-4139-9550-11121d38c7a0.png)

![image](https://user-images.githubusercontent.com/53864204/129173766-1ffd82dd-d4d5-4ece-bbca-7aa7df50d987.png)

**Comment by destinokm** [comment]
同样的问题， 日志提示grpc启动失败

**Comment by tikazyq** [comment]
Fixed in the newest update

**Comment by haoweicrushu** [comment]
same issue

```sh
crawlab_master          | context deadline exceeded
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:268 github.com/crawlab-team/crawlab-core/grpc/client.(*Client)._connect()
crawlab_master          | /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
crawlab_master          | /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/node/service/worker_service.go:46 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
crawlab_master          | /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
crawlab_master          | 2022/05/28 01:58:56 error grpc client connect error: grpc error: client failed to start. reattempt in 0.6 seconds...
crawlab_worker          | context deadline exceeded
crawlab_worker          | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
crawlab_worker          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:268 github.com/crawlab-team/crawlab-core/grpc/client.(*Client)._connect()
crawlab_worker          | /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
crawlab_worker          | /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
crawlab_worker          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
crawlab_worker          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
crawlab_worker          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/node/service/worker_service.go:46 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
crawlab_master          | grpc error: client failed to start
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/utils/backoff.go:13 github.com/crawlab-team/crawlab-core/utils.BackoffErrorNotify.func1()
crawlab_master          | /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:69 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
crawlab_master          | /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
crawlab_worker          | /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
crawlab_master          | /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0/node/service/worker_service.go:46 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
crawlab_master          | /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
```

```yaml
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: Y
      CRAWLAB_MONGO_HOST: mongo
    ports:
      - "8080:8080" # frontend port mapping 前端端口映射
    depends_on:
      - mongo
    # volumes:
    #   - "/opt/crawlab/master:/data"  # data persistent 持久化数据
  worker:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_worker
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
    depends_on:
      - mongo
    # volumes:
    #   - "/opt/crawlab/worker:/data"  # data persistent 持久化数据
  mongo:
    image: mongo:4.2
    #restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - "/opt/crawlab/mongo/data/db:/data/db"  # data persistent 持久化数据
    # ports:
    #   - "27017:27017"  # expose port to host machine 暴露接口到宿主机

```

**Comment by tikazyq** [comment]
You can refer to this solution: https://github.com/crawlab-team/crawlab/issues/1110#issuecomment-1139189706

```yaml
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    ports:
      - "8080:8080" # frontend port mapping 前端端口映射
    depends_on:
      - mongo
    # volumes:
    #   - "/opt/crawlab/master:/data"  # data persistent 持久化数据
  worker:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_worker
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
    depends_on:
      - mongo
    # volumes:
    #   - "/opt/crawlab/worker:/data"  # data persistent 持久化数据
  mongo:
    image: mongo:4.2
    #restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - "/opt/crawlab/mongo/data/db:/data/db"  # data persistent 持久化数据
    # ports:
    #   - "27017:27017"  # expose port to host machine 暴露接口到宿主机
```
